FROM ghcr.io/astral-sh/uv:python3.12-bookworm

ENV DGLBACKEND=pytorch
ENV MATGL_BACKEND=DGL


RUN uv pip install dgl -f https://data.dgl.ai/wheels/cu121/repo.html --system
RUN uv pip install dglgo -f https://data.dgl.ai/wheels-test/repo.html --system
RUN uv pip install torch==2.2.0 torchdata==0.7.1 --system
RUN uv pip install matgl --system
